components_manager:
  task_processors:
    main-task-processor:
      worker_threads: 4

    fs-task-processor:
      worker_threads: 1

  default_task_processor: main-task-processor
 
  components:
    server:
      listener:
        port: 8080
    logging:
      loggers:
        default:
          file_path: '@stderr'
          level: debug
          overflow_behavior: discard

    boolean-search-handler:
      path: /search/boolean
      method: GET
      task_processor: main-task-processor

    quote-search-handler:
      path: /search/quote
      method: GET
      task_processor: main-task-processor

    mongo-index:
      dbconnection: mongodb://localhost:27017/index
 
    http-client:
      pool-statistics-disable: true
      thread-name-prefix: index-http-client
      threads: 2
      fs-task-processor: fs-task-processor
      user-agent: searcher-service 1.0

    requester-service:
      fs-task-processor: fs-task-processor
      user-agent: searcher-service 1.0
      
