components_manager:
    task_processors:             
        main-task-processor:          
            worker_threads: 4         
 
        fs-task-processor:            
            worker_threads: 1
 
    components:                       
        server:
            listener:                 
                port: 8080            
        logging:
            loggers:
                default:
                    file_path: '/logs/db.log'
                    level: debug
                    overflow_behavior: discard  
 
        insert-handler:             
            path: /insert           
            method: POST            
            task_processor: fs-task-processor

        document-handler:
          path: /document
          method: GET
          task_processor: main-task-processor

        token-handler:
          path: /token
          method: GET
          task_processor: main-task-processor
